### ISSUE TITLE
Cellprofiler generates a lot of java warnings on startup due to ImageJ

### ISSUE THREAD

**Issue by samfux84** [CellProfiler/java#24]
Hi,

I installed CellProfiler 2.2.0 using Prokaryote 1.0.10. When I start cellprofiler, then I receive a lot of java warnings and exceptions:

[sfux@euler01 ~]$ cellprofiler -L 20
Picked up _JAVA_OPTIONS: -XX:ParallelGCThreads=1
java.lang.IllegalArgumentException: Cannot handle replace call to list in ij.Menus's public static synchronized java.lang.String[] getPlugins()
        at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:725)
        at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:650)
        at net.imagej.patcher.LegacyExtensions.addExtraPlugins(LegacyExtensions.java:477)
        at net.imagej.patcher.LegacyExtensions.injectHooks(LegacyExtensions.java:175)
        at net.imagej.patcher.LegacyInjector.inject(LegacyInjector.java:308)
        at net.imagej.patcher.LegacyInjector.injectHooks(LegacyInjector.java:109)
        at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:101)
        at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:495)
        at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:397)
        at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:376)
        at net.imagej.patcher.JavaAgent.preinit(JavaAgent.java:147)
        at net.imagej.patcher.JavaAgent.premain(JavaAgent.java:95)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)

According to https://github.com/imagej/imagej-tutorials/issues/24 this problem can be solved by updating ImageJ. Would it be possible to bundle a newer version of ImageJ with prokaryote ?

Thank you.

Best regards

Sam

**Comment by samfux84** [comment]
I am sorry, there was a typo in my previous message. I used verison 1.0.11, not 1.0.10
