### ISSUE TITLE
java.util.zip.ZipException: invalid CEN header (bad signature)

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/java#6]
I'm unable to load any classes from the prokaryote-1.0.2.jar when I access it using the javabridge on the cluster, e.g. `javabridge.JClassWrapper("loci.common.Location")` gives me a classpath error. The jar does work on my machine with Java 8 installed.

Running javap on the jar produced by Maven results in the following error which makes me think that the zip structure of the jar is bad:

```
javap" -classpath target/prokaryote-1.0.2.jar loci.common.Location
java.util.zip.ZipException: invalid CEN header (bad signature)
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:127)
    at java.util.jar.JarFile.<init>(JarFile.java:136)
    at java.util.jar.JarFile.<init>(JarFile.java:100)
    at sun.tools.javap.JavapEnvironment.resolveclasspathhelper(JavapEnvironment.java:312)
    at sun.tools.javap.JavapEnvironment.resolveclasspath(JavapEnvironment.java:242)
    at sun.tools.javap.JavapEnvironment.resolvefilename(JavapEnvironment.java:197)
    at sun.tools.javap.JavapEnvironment.getFileInputStream(JavapEnvironment.java:133)
    at sun.tools.javap.Main.displayResults(Main.java:198)
    at sun.tools.javap.Main.perform(Main.java:61)
    at sun.tools.javap.Main.entry(Main.java:49)
    at sun.tools.javap.Main.main(Main.java:34)
ERROR:fatal exception
java.util.zip.ZipException: invalid CEN header (bad signature)
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:127)
    at java.util.jar.JarFile.<init>(JarFile.java:136)
    at java.util.jar.JarFile.<init>(JarFile.java:100)
    at sun.tools.javap.JavapEnvironment.resolveclasspathhelper(JavapEnvironment.java:312)
    at sun.tools.javap.JavapEnvironment.resolveclasspath(JavapEnvironment.java:242)
    at sun.tools.javap.JavapEnvironment.resolvefilename(JavapEnvironment.java:197)
    at sun.tools.javap.JavapEnvironment.getFileInputStream(JavapEnvironment.java:133)
    at sun.tools.javap.Main.displayResults(Main.java:198)
    at sun.tools.javap.Main.perform(Main.java:61)
    at sun.tools.javap.Main.entry(Main.java:49)
    at sun.tools.javap.Main.main(Main.java:34)
ERROR:fatal exception
java.util.zip.ZipException: invalid CEN header (bad signature)
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:127)
    at java.util.jar.JarFile.<init>(JarFile.java:136)
    at java.util.jar.JarFile.<init>(JarFile.java:100)
    at sun.tools.javap.JavapEnvironment.resolveclasspathhelper(JavapEnvironment.java:312)
    at sun.tools.javap.JavapEnvironment.resolveclasspath(JavapEnvironment.java:242)
    at sun.tools.javap.JavapEnvironment.resolvefilename(JavapEnvironment.java:197)
    at sun.tools.javap.JavapEnvironment.getFileInputStream(JavapEnvironment.java:133)
    at sun.tools.javap.Main.displayResults(Main.java:198)
    at sun.tools.javap.Main.perform(Main.java:61)
    at sun.tools.javap.Main.entry(Main.java:49)
    at sun.tools.javap.Main.main(Main.java:34)
ERROR:fatal exception
ERROR:Could not find loci.common.Location
```

**Comment by LeeKamentsky** [comment]
What I got to work:

Explicitly specify that the jar supports Java 6 by setting the target to 1.6.
Set JAVA_HOME to point at the Java 6 JDK.
Use Maven v 3.2.5 to build because Maven 3.3.x does not run with a Java 6 JDK.

:confused: 

Maybe there is a solution with fewer moving parts, but I did test some of them.
